
import React from 'react';
import './App.css';

// Imports the Amplify library from 'aws-amplify' package. This is used to configure your app to interact with AWS services.
import {Amplify} from 'aws-amplify';

// Imports the Authenticator and withAuthenticator components from '@aws-amplify/ui-react'.
// Authenticator is a React component that provides a ready-to-use sign-in and sign-up UI.
// withAuthenticator is a higher-order component that wraps your app component to enforce authentication.
import { Authenticator, withAuthenticator } from '@aws-amplify/ui-react';

// Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.
import '@aws-amplify/ui-react/styles.css';

// Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.
import awsExports from './aws-exports';

// Imports the Quiz component from Quiz.js for use in this file.
import Quiz from './components/Quiz.jsx';

// Configures the Amplify library with the settings from aws-exports.js, which includes all the AWS service configurations for this project.
Amplify.configure(awsExports);

function App() {
  return (
    <div className="App box-border ">
      <Authenticator>
        {({ signOut }) => (
          <main>
            <header className=' flex flex-col justify-center  items-center h-screen bg-slate-400 relative'>
              <h1 className='text-center font-bold text-white text-4xl mb-6'>Quiz App</h1>
              {/* Quiz Component */}
              <Quiz />
              {/* Sign Out Button */}
              <button  onClick={signOut} className='bg-black hover:bg-white text-white hover:text-black rounded-2xl px-6 py-2 text-sm font bold hover:border-2 border-2 border-black hover:font-bold absolute top-6 right-10'>Sign Out</button>
            </header>
          </main>
        )}
      </Authenticator>
    </div>
  );
}

export default withAuthenticator(App);
